---
- name: Update apt cache (Debian)
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Update dnf cache (RedHat)
  dnf:
    update_cache: yes
  when: ansible_os_family == "RedHat"
